### ISSUE TITLE
More info?

### ISSUE THREAD

**Issue by melMass** [needle-tools/timeline-mixer#4]
Hi,

Is there a blog post or something about this repo? I'm not sure of what it does, additive animation on top of the timeline?

Thanks

**Comment by marwie** [comment]
Hey, 

it does allow for blending/overriding between animation controlled by timeline and other animation clips like this
https://twitter.com/marcel_wiessler/status/1306319332163702785

**Comment by melMass** [comment]
Thanks! That's what I was looking for!

**Comment by marwie** [comment]
Do you mean in terms of functionality or info? :)

**Comment by melMass** [comment]
Both :) !

**Comment by marwie** [comment]
haha thanks, I'm glad.

Btw thanks for the motivation to add some docs and publish it on OpenUPM :)
https://openupm.com/packages/com.needle.animation.timelinemixer/
